# Generated by Django 4.2 on 2025-09-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True),
        ),
    ]
